# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_state\
$git_status\
[](fg:#394260 bg:#212736)\
$java\
$nodejs\
$dart\
[](fg:#212736)\
$line_break\
$character"""

palette = "tokyonight_storm"


[directory]
truncation_length = 3
truncate_to_repo = false
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = "[[ $symbol $branch](fg:#769ff0 bg:#394260)]($style)"


[git_status]
conflicted = "[󰹳${count}](fg:red bg:#394260)"
ahead = "[󰁝${count}](fg:green bg:#394260)"
behind = "[󰁅${count}](fg:yellow bg:#394260)"
diverged = "[󰹹](fg:bold yellow bg:#394260)"
untracked = "[?${count}](fg:cyan bg:#394260)"
stashed = "[\\$${count}](fg:blue bg:#394260)"
modified = "[!${count}](fg:magenta bg:#394260)"
staged = "[+${count}](fg:green bg:#394260)"
renamed = "[󱞩${count}](fg:cyan bg:#394260)"
deleted = "[󰅖${count}](fg:red bg:#394260)"
style = "bg:#394269"
format = "[[ $all_status$ahead_behind ](fg:#769ff0 bg:#394260)]($style)"


[character]
success_symbol = "[❯](bold fg:green)"
error_symbol = "[❯](bold fg:red)"


[package]
disabled = true

[java]
symbol = ""
style = "bg:#212736"
version_format = "v${major}"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:#212736"
version_format = "v${major}"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[dart]
symbol = ""
style = "bg:#212736"
version_format = "v${major}"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'


[palettes.tokyonight_storm]
black = "#414868"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#C0CAF5"
foreground = "#c0caf5"
background = "#24283b"
