# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:foreground fg:black)\
[](bg:blue fg:foreground)\
$directory\
[](fg:blue bg:black)\
$git_branch\
[](fg:black bg:background)\
$git_state\
$git_status\
$java\
$nodejs\
$dart\
\n$character"""

palette = "tokyonight_storm"


[directory]
style = "fg:#e3e5e5 bg:blue"
format = "[ $path ]($style)"


[git_branch]
symbol = ""
style = "bg:background"
format = '[[ $symbol $branch ](fg:blue bg:black)]($style)'

[git_status]
conflicted = "[󰹳${count}](red)"
ahead = "[󰁝${count}](green)"
behind = "[󰁅${count}](yellow)"
diverged = "[󰹹](bold yellow)"
untracked = "[?${count}](cyan)"
stashed = "[\\$${count}](blue)"
modified = "[!${count}](magenta)"
staged = "[+${count}](green)"
renamed = "[󱞩${count}](cyan)"
deleted = "[󰅖${count}](red)"
format = '[ $all_status$ahead_behind]($style)'


[character]
success_symbol = "[❯](fg:green)"
error_symbol = "[](fg:red)"


[package]
disabled = true

[java]
symbol = ""
version_format = "v${major}"
format = '[[ ${symbol} (${version}) ](fg:blue)]($style)'

[nodejs]
symbol = "󰎙"
version_format = "v${major}"
format = '[[ ${symbol} (${version}) ](fg:blue)]($style)'

[dart]
symbol = ""
version_format = "v${major}"
format = '[[ ${symbol} (${version}) ](fg:blue)]($style)'

[palettes.tokyonight_storm]
black = "#414868"
red = "#F7768E"
green = "#9ECE6A"
yellow = "#E0AF68"
blue = "#7AA2F7"
magenta = "#BB9AF7"
cyan = "#7DCFFF"
white = "#C0CAF5"
foreground = "#c0caf5"
background = "#24283b"
