# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[package]
disabled = true

[java]
symbol = " "
style = "red"
version_format = "v${major}"
format = "[${symbol}(${version} )]($style)"

[nodejs]
version_format = "v${major}"
format = "[${symbol}(${version} )]($style)"

[dart]
version_format = "v${major}"
format = "[${symbol}(${version} )]($style)"
